[tool.poetry]
name = "alot"
version = "0.10"
description = "Terminal MUA using notmuch mail"
authors = ["Patrick Totzke <patricktotzke@gmail.com>"]
readme = "README.md"
license = "GPL-3.0-or-later"
repository = "https://github.com/pazz/alot"
documentation = "https://alot.readthedocs.io/en/latest/"
classifiers=[
	'Development Status :: 4 - Beta',
	'Environment :: Console :: Curses',
	'Framework :: AsyncIO',
	'Intended Audience :: End Users/Desktop',
	'Operating System :: POSIX',
	'Programming Language :: Python :: 3.6',
	'Programming Language :: Python :: 3.7',
	'Programming Language :: Python :: 3 :: Only',
	'Topic :: Communications :: Email :: Email Clients (MUA)',
	'Topic :: Database :: Front-Ends',
]


[tool.poetry.dependencies]
python = ">=3.6"
notmuch2= ">=0.1"
urwid = ">=1.3.0"
urwidtrees = ">=1.0.3"
twisted = ">=18.4.0"
python-magic = "*"
configobj = ">=4.7.0"
gpg = "*"

[tool.poetry.dev-dependencies]
pycodestyle = "*"
pytest = "*"

[tool.poetry.scripts]
alot = "alot.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
